
file-upload=C:/Users/This  PC/IdeaProjects/vocaboost/src/main/resources/static/images/avatar/
file-upload-subject=C:/Users/This  PC/IdeaProjects/vocaboost/src/main/resources/static/images/subject/
file-upload-topic=C:/Users/This  PC/IdeaProjects/vocaboost/src/main/resources/static/images/topic/
